# Generated by Django 2.0.7 on 2018-08-13 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('Mopid', models.CharField(max_length=50, verbose_name='用户昵称')),
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户openid')),
                ('date', models.DateField(verbose_name='日期')),
            ],
            options={
                'verbose_name': '用户购物车',
            },
        ),
        migrations.CreateModel(
            name='good',
            fields=[
                ('memberid', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('Mopid', models.CharField(max_length=50, verbose_name='用户openid')),
                ('id', models.CharField(max_length=10, verbose_name='商品编号')),
                ('title', models.CharField(max_length=10, verbose_name='商品名称')),
                ('price', models.CharField(max_length=10, verbose_name='商品售价')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='商品数量')),
                ('selected', models.BooleanField(default=False, verbose_name='是否勾选')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.cart')),
            ],
            options={
                'verbose_name': '商品',
            },
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='商品编号')),
                ('image', models.CharField(max_length=50, verbose_name='图片路径')),
                ('title', models.CharField(max_length=10, verbose_name='商品名称')),
                ('price', models.CharField(max_length=10, verbose_name='商品售价')),
                ('stock', models.CharField(max_length=10, verbose_name='有/无货')),
                ('detail', models.CharField(max_length=10, verbose_name='详情')),
                ('parameter', models.CharField(max_length=10, verbose_name='商品规格')),
                ('service', models.CharField(max_length=10, verbose_name='售后说明')),
            ],
            options={
                'verbose_name': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Mopid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户openid')),
                ('session_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='session_key')),
                ('Mcardnum2', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户信息2')),
                ('Mcardnum3', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户信息3')),
                ('Mcardnum4', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户信息4')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('Mtotal', models.CharField(blank=True, max_length=50, null=True, verbose_name='累计消费')),
                ('Mbalance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='我的钱包')),
            ],
            options={
                'verbose_name': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('ordernumber', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户订单号')),
                ('nickname', models.CharField(max_length=50, verbose_name='用户昵称')),
                ('openid', models.CharField(max_length=50, verbose_name='用户openid')),
                ('date', models.DateField(verbose_name='日期')),
            ],
            options={
                'verbose_name': '用户订单',
            },
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('mopid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='weixin.Member')),
                ('up', models.CharField(blank=True, max_length=50, null=True, verbose_name='up')),
                ('down1', models.CharField(blank=True, max_length=50, null=True, verbose_name='down1')),
                ('down2', models.CharField(blank=True, max_length=50, null=True, verbose_name='down2')),
                ('down3', models.CharField(blank=True, max_length=50, null=True, verbose_name='down3')),
            ],
            options={
                'verbose_name': '团队信息',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weixin.orders'),
        ),
    ]
